version: '3.8'
services:
  app:
    build: .
    ports:
      - "6000:5000"
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=products
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
    ports:
      - "3406:3306"